### ISSUE TITLE
Get Energy Data Files (gbxml / doe / eplus)

### ISSUE THREAD

**Issue by eertugrul** [tt-acm/EnergyAnalysisForDynamo#25]
Requested from GBS team to create API call to get/download the energy files.
The call uri signature would be:
internal static string GetRunResultsUri = @"/v1/run/results/{0}/{1}/{2}"; // 0 = runId, 1 = altRunId, 2=response payload (gbxml/doe/eplus)

Follow up with GBS team. Placeholder Node (the code is written too):
![image](https://cloud.githubusercontent.com/assets/4672688/4279400/deb87d2a-3d20-11e4-9bac-56ad7ad35be7.png)

**Comment by bhowes-tt** [comment]
This is working - see sample file number 6.
