### ISSUE TITLE
TEST: try to upload a list  of gbxml files with RunEnergyAnalysisNode

### ISSUE THREAD

**Issue by eertugrul** [tt-acm/EnergyAnalysisForDynamo#60]
@bhowes-tt told he encountered runtime error while sending multiple gbxml files at once.

**Comment by eertugrul** [comment]
enhancement on RunAnalysis node as discussed!

![image](https://cloud.githubusercontent.com/assets/4672688/6051037/8ed1145c-ac92-11e4-9e42-2aae94ed95ce.png)

**Comment by bhowes-tt** [comment]
Nice!!!  Did you include the try / catch code so that if one run fails all subsequent runs will be attempted?

**Comment by eertugrul** [comment]
Yes sir !
If one of the run is failed to upload for any reason,it doesn't sink the ship. it goes to next run. But the runId returns as null in the list item for the failed gbxml,  and also report indicates the file name
