### ISSUE TITLE
Sign into GBS Warning

### ISSUE THREAD

**Issue by mostaphaRoudsari** [tt-acm/EnergyAnalysisForDynamo#71]
"- User should be prompted to sign into GBS if they haven’t yet.
o	Currently, the warning for RunAnalysis.RunEnergyAnalysis if I forget to sign in is not helpful."

![gbslogin](https://cloud.githubusercontent.com/assets/2915573/5073258/af6365b2-6e4e-11e4-9244-67bfb127cff4.png)

This looks like an issue with Null ProjectId and not login check but we need to test it again.

**Comment by eertugrul** [comment]
@mostaphaRoudsari  I couldn't repeat the problem !

**Comment by bhowes-tt** [comment]
I could, but it's a dynamo problem.  The issue arises when a null is passed into the ProjectId input - our code never even executes because Dynamo can't cast a null to an Int.
