### ISSUE TITLE
Testing Our Library

### ISSUE THREAD

**Issue by eertugrul** [tt-acm/EnergyAnalysisForDynamo#81]
notes from Ian's testing call last week.

system testing NuGet packages for dynamo can be find here:
https://github.com/DynamoDS/Dynamo/tree/master/tools/NuGet

If I am remember correctly, we need implement three testing classes:
dynamo nodes,
dynamo UI nodes,
sample files test 

Use SystemTestBase  and [TextFixture]

**Comment by eertugrul** [comment]
@bhowes-tt reminder !

**Comment by bhowes-tt** [comment]
Finally in process!  I worked with Ian to get a hello world working with the Revit Test Framework, which was completed as part of pull request #103 

Now I'm working on a branch called feature_ExampleFileTesting creating meaningful system tests.  I have minimal tests for all samples, and have created explicit tests for a few files.  

Super super useful already!
![image](https://cloud.githubusercontent.com/assets/3171551/8191911/e5ad107e-1438-11e5-988e-ce7376d52959.png)

**Comment by bhowes-tt** [comment]
So close...  everything is working except example 1e.

**Comment by eertugrul** [comment]
@bhowes-tt 
I am following the steps here for creating testing framework for DynamoSAP as well. I forked RTF repo and install the RTF.exe and run GUI for EA4D testing project. I constantly get this error. " A reference type could not be loaded."
What I am missing here ?
![image](https://cloud.githubusercontent.com/assets/4672688/8291826/eb8479d6-18f9-11e5-802f-bb4f2bb269f4.png)

**Comment by bhowes-tt** [comment]
@eertugrul You need to build the RTF project from source and use the compiled exe for testing - @ikeough hasn't updated the installer yet.  Let me know if that does it...

**Comment by eertugrul** [comment]
no luck, might be the Dynamo version I use ? since some testing/srvices dlls are referenced from Dynamo08 folder.

**Comment by eertugrul** [comment]
never mind, it worked, I have typed additional resolution directories first then chose the testing assembly. :+1:

**Comment by bhowes-tt** [comment]
Success!!!

![image](https://cloud.githubusercontent.com/assets/3171551/8438159/2ce6cc7e-1f32-11e5-9df4-344b7f45ec45.png)


All samples running successfully using our testing framework.  The tests are essentially pass / fail system tests - nothing too granular.  BUT it works!

Also for the record - sample files had to be saved to run manually.

**Comment by bhowes-tt** [comment]
So glad to close this...
