### ISSUE TITLE
extend GetEnergySettings to match SetEnergySettings

### ISSUE THREAD

**Issue by bhowes-tt** [tt-acm/EnergyAnalysisForDynamo#85]
We should add all of the new properties to the Get EnergySettings node.
![image](https://cloud.githubusercontent.com/assets/3171551/5906202/d0238af6-a563-11e4-8d7b-1217d4e843bc.png)

**Comment by mostaphaRoudsari** [comment]
![image](https://cloud.githubusercontent.com/assets/2915573/5940598/ee4691fa-a6d9-11e4-95c3-bad7df98bbb9.png)
