### ISSUE TITLE
show how to set all surface types in example 1b

### ISSUE THREAD

**Issue by bhowes-tt** [tt-acm/EnergyAnalysisForDynamo#86]
![image](https://cloud.githubusercontent.com/assets/3171551/5906431/800eed4c-a565-11e4-8f93-0e1f40ba2679.png)

**Comment by mostaphaRoudsari** [comment]
@bhowes-tt Looks like you have already addressed this: e51f6f3fb356c0bc195970acd5edb760ae7f6658

**Comment by bhowes-tt** [comment]
@mostaphaRoudsari maybe I should have said that we need to prove that we can set parameters on all surface types.  Recall that we're going to use these samples (or similar files) for system testing.  Relates to issue #81

**Comment by bhowes-tt** [comment]
OK just talked to @mostaphaRoudsari in person - we'll keep the sample files simple and create more exhaustive files for testing.
