### ISSUE TITLE
SetSurfaceConceptualConstruction fails when setting glazing type

### ISSUE THREAD

**Issue by bhowes-tt** [tt-acm/EnergyAnalysisForDynamo#88]
@mostaphaRoudsari and I looked at this, and it looks like the PrepareEnergyModel.getConceptualConstructionIdFromName method is failing.  See example file 1e to test.

**Comment by mostaphaRoudsari** [comment]
It turned out to be more than only glz. Anything other than walls would fail. It is fixed now.
![image](https://cloud.githubusercontent.com/assets/2915573/6008027/71624dca-aaec-11e4-97d3-f96c4d225d63.png)
