### ISSUE TITLE
GetAnalysisResults.LoadAnalysisResults failing

### ISSUE THREAD

**Issue by bhowes-tt** [tt-acm/EnergyAnalysisForDynamo#89]
I found this while testing sample file 5a.  I tried a number of different runs and projects - all showed the same error.

![image](https://cloud.githubusercontent.com/assets/3171551/5946197/f0b302a2-a701-11e4-96c2-aa18dbed7bf2.png)

**Comment by eertugrul** [comment]
@bhowes-tt  Seems there was something change on encoder of web responses, any way I have changed the default byte type to UTF-8 for json de-serializer, so this solved the problem.
