### ISSUE TITLE
ADD Sync Version fof GetAnalysis node

### ISSUE THREAD

**Issue by eertugrul** [tt-acm/EnergyAnalysisForDynamo#92]
"Sync version will block the dynamo during solution since it will wait until the simulation to be completed and returns the results"

**Comment by mostaphaRoudsari** [comment]
@eertugrul this sounds great to me as far as it is an option that can be changed. Is it how you want to implement it?

**Comment by eertugrul** [comment]
@mostaphaRoudsari 
we thought to have two separate versions of Get Results nodes!  Sync version will block the dynamo during solution since it will wait until the simulation to be completed and returns the results. Async version just checks simulation(run) status once and throw an exception if it is not completed. 

Do u prefer to have one node with additional Boolean input , default set is False!

**Comment by mostaphaRoudsari** [comment]
@eertugrul thanks. As far as I have the option to select between them it should be fine. I would probably keep it to a single node but that's me who likes big nodes with so many options. Separating them into two nodes will result in cleaner smaller nodes.

**Comment by eertugrul** [comment]
@mostaphaRoudsari I have added a boolean input to existing node that enables the synchronization with simulations.

looks good!
