### ISSUE TITLE
Dropdown nodes don't work in Dynamo 7.5+

### ISSUE THREAD

**Issue by mostaphaRoudsari** [tt-acm/EnergyAnalysisForDynamo#93]
@BPOpt informed me that drop-down nodes doesn't work anymore in new versions of Dynamo.

@ikeough we implemented this based on your example file last time and it was pretty straight forward to do. Is there an updated example that we can use to update the nodes? [Here is the current implementation] (https://github.com/tt-acm/EnergyAnalysisForDynamo/blob/master/src/EnergyAnalysisForDynamo_UI/EnergyAnalysisForDynamoDropdowns.cs)

Thanks!

cc: @pboyer, @tatlin

**Comment by bhowes-tt** [comment]
I got something working using 0.8.0 ... but the code feels off somehow, and the dropdowns don't seem to serialize their state when closing / re-opening a saved file.  

Most recent source is here if anyone is interested:
https://github.com/tt-acm/EnergyAnalysisForDynamo/blob/master/src/EnergyAnalysisForDynamo_UI/EnergyAnalysisForDynamoDropdowns.cs

I'll leave this open until we are sure these are working perfectly.

**Comment by eertugrul** [comment]
@bhowes-tt they work well. Closing the issue.

**Comment by bhowes-tt** [comment]
I'm still seeing blank dropdowns when opening files...  Reopening this.

**Comment by bhowes-tt** [comment]
Fixed!  Thanks @ikeough for the help here:
https://github.com/DynamoDS/Dynamo/commit/19d37337742f87bbf4bc6283de10ee7bbf7927a1

:boat: :octopus:

**Comment by bhowes-tt** [comment]
Uggghhhhhh .... not quite.  Dropdown nodes' states are not saved / recalled when closing and re-opening a file.  When opening a file, all dropdowns are set to the first value in the list, not the item that was selected when the file was saved.

**Comment by BPOpt** [comment]
Hi,
I tried the Energy Analysis Package that is released on June 5th with Dynamo Daily Build and Revit 2016. The dropdown nodes are still unresolved. Can you share push the version that has dropdowns working. I can work with it till the updated version that keeps dropdown values is released.

**Comment by bhowes-tt** [comment]
@BPOpt - thanks for the heads up.  I haven't tested with a daily recently, and I know there is still at least one major issue on top of 0.8.0.  Stay tuned...

**Comment by bhowes-tt** [comment]
These latest fixes seem to do the trick.  Dropdowns are working in 0.8.0, including recalling their state when opening a file.
