### ISSUE TITLE
Update all sample files for Dynamo 0.8

### ISSUE THREAD

**Issue by bhowes-tt** [tt-acm/EnergyAnalysisForDynamo#99]
Verify that all sample files are up to date and work as designed.  Samples 3a and 3b were stale when @eertugrul and I were looking through them today, for example.

**Comment by eertugrul** [comment]
@bhowes-tt  Could u please look at the sample  ex1e.Separete Surface by Orientation with sample fancy model ?
I think 'Separate Srfs By Orientation' node works as expected in simple model but I think the notes doesn't refer the surface orientation as South, West facing in Fancy model.  if the intent is to find South, West, East,North facing facades we should use range of angles in the node to group per North vector, currently checking  angle 2 Y axis, and model's site location and rotation might be different than Revit project location, and rotation.

Have you ever checked EnergyAnalysisSurface.Name Property ?
"
N = Orientation [N/NE/E/SE/S/SW/W/NW/N/T/B/X] (every surface within the sector of 22.5 degrees from the north vector gets the letter N etc) (horizontal surfaces facing upwards get the letter T for top, downwards B for bottom) (shading surfaces get the letter X for differentiation). "

http://revitapisearch.com/html/b0299541-a03c-bb38-c71b-de78ea14d1a7.htm

**Comment by eertugrul** [comment]
Project Position members (angle from True North) would help us to map the Surface Orientation  properly.
http://help.autodesk.com/view/RVT/2014/ENU/?guid=GUID-A1B6B145-132D-47EF-8B2E-DB1659CB6A0A

**Comment by bhowes-tt** [comment]
@eertugrul as discussed - I think it's fine.  This example is set up to work with our simple example file in particular (and 4 sided masses in general).

**Comment by eertugrul** [comment]
I added a note that the sample file ex1e should run with simple mass model.
